language: python
python:
  - 2.7.15
cache: pip
install:
  - pip install -r requirements.txt
script:
  - make html
  - sphinx-intl build
  - sphinx-build -b html source build/html/ja -D language='ja'
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local_dir: build/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master
