language: python
python:
  - 3.7
cache: pip

before_install:
  - cd source/resources/examples/typescript
  - npm install
  - npm run lint
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install -r requirements.txt
script:
  - make gettext
deploy:
  provider: script
  script: bash .tx/deploy.sh
  on:
    branch: master
