language: python
python:
  - 3.7
cache: pip
install:
  - pip install -r requirements.txt
  - pip install transifex-client
  - cd source/resources/examples/typescript && npm install
script:
  - make gettext
  - make html
  - cd source/resources/examples/typescript && npm run lint
deploy:
  provider: script
  script:
    - echo $'[https://www.transifex.com]\nhostname = https://api.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\n' > ~/.transifexrc
    - tx push -s
  on:
    branch: master
