language: python
python:
  - 3.7
cache: pip

before_install:
  - cd source/resources/examples/typescript
  - npm install
  - npm run lint
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install -r requirements.txt
script:
  - make gettext
  - make html
deploy:
  provider: script
  script:
    - pip install transifex-client
    - echo $'[https://www.transifex.com]\nhostname = https://api.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\n' > ~/.transifexrc
    - tx push -s
  on:
    branch: master
